filebeat.inputs:
  - type: filestream
    enabled: true
    id: laravel-log-filestream
    paths:
      - "/usr/share/filebeat/ingest_data/playlogstash/*.log"
      - ingest_data/playlogstash/*.log
    multiline.pattern: '^\['   # 假设每条日志以 [ 开头
    multiline.negate: true
    multiline.match: after
    fields: # 自定义字段
      app: playlogstash
      type: laravel
      timezone: "Asia/Shanghai"

    fields_under_root: false
    ignore_older: 72h

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# processors:
#   - add_docker_metadata: ~


# setup.kibana:
#   host: ${KIBANA_HOSTS}
#   username: ${ELASTIC_USER}
#   password: ${ELASTIC_PASSWORD}

# output.elasticsearch:
#   hosts: ${ELASTIC_HOSTS}
#   username: ${ELASTIC_USER}
#   password: ${ELASTIC_PASSWORD}
  # ssl.enabled: true
  # ssl.certificate_authorities: "certs/ca/ca.crt"

output.logstash:
  hosts: ${LOGSTASH_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
